name: juros_calculator
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_masked_text: ^0.8.0
  intl: ^0.16.1
  datetime_picker_formfield: ^1.0.0
  custom_radio_grouped_button: ^1.0.0
  dynamic_theme: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true